RAID = [
    "May you have such an incredibly special birthday that every day afterward starts and ends with love and Peace of Mind.Happy Birthday!",
    "A Birthday is just another day where you go to work and people give you love.Age is just a state of mind and you are as old as you think you are.You have to count your blessings and be happy.Happy Birthday Elena!", 
    "Wishing you a day that is as special in every way as you are. Enjoy your Day!", 
    "I hope your special day will bring you lots of happiness love and fun. You deserve them a lot. Enjoy.Happy Birthday Elena!", 
    "I hope your special day will bring you lots of happiness love and fun. You deserve them a lot. Enjoy.Happy Birthday Elena!", 
    "Thinking of you with Love on your Birthday and wishing you everything that brings you happiness today and always.Happy Birthday!", 
    "Wishing you a day filled with many pleasant surprises and tons of gifts. A lot of love for you on this special day. A very Happy Birthday to one of the sweet persons I have known. Keep Smiling.Happy Birthday!", 
    "The best things are always those which we cannot have what we wait for years. Those are always the most beautiful dreams colorful and from a fairy tale world. Today on your birthday I wish you receive what you always dreamt of! All the Best to you.Happy Birthday!", 
    "Today is your day. Dance with fairies ride a unicorn swim with mermaids and chase rainbows.", 
    "You have the biggest heart in the world! Thank you for keeping me in it. Happy birthday!", 
    "Happy birthday to a person that’s charming talented and witty and reminds me a lot of myself.", 
    "May your day be as beautiful as you. Happy birthday, friend!", 
    "Happy birthday bestie me tuje nhi chord skta kabhi", 
    "You are my kind of crazy and that is what life is really about! Happy birthday.", 
    "ऐसी क्या दुआ दूँ आपको जो आपके लबों पर ख़ुशी के फूल खिला देबस ये दुआ है मेरी सितारों सी रौशनी खुदा आपकी तकदीर बना दे। जन्मदिन मुबारक!",
    "may ur day b filled with laughteron dis ur spcl day many finest thing in lyf always come ur way..Happy b’day..", 
    "May your day be as beautiful as you. Happy birthday, friend!", 
    "Someone I love was born today.", 
    "Happy birthday @sh_elenaa ", 
    "Happy birthday crime partener (kaand partner) ", 
    "Happy birthday yaara 🥰🥰", 
    "A birthday means that you are a year older but a birthday party means you get to act 10 years younger. Enjoy the party! ", 
    "Another year of you is reason enough for us all to celebrate with cake!", 
    "You’re not really grown up ’til you’ve realized your Mother was always right.", 
    "Here’s to the sweetest and loveliest person I know. Happy birthday.", 
    "Hope your birthday is as wonderful and extraordinary as you are. ", 
    "God gave us the gift of life it is up to us to give ourselves the gift of living well.", 
    "You take away all the other luxuries in life and if you can make someone smile and laugh you have given the most special gift happiness.", 
    "Another year went by and you are just as charming a bit wiser and a lot more gorgeous. Happy birthday!", 
    "Happy birthday @sh_elenaa ", 
    "Happy birthday bhootni ", 
    "Happy birthday meri bestie ", 
    "Happy birthday elena jo tu chahati vo tuje jaldi se jaldi mile bs boyfriend nhi hona chahiye 🤣🤣", 
    "Sun tu h to bhootni but tujbpe line bhi marta hu 🤣🤣", 
    "In this day don’t forget you never gave up remember how you faced every battle and know-how proud I am to be your friend. Happy birthday!", 
    "Thirty-five is a very attractive age. London society is full of women of the very highest birth who have of their own free choice, remained thirty-five for years.", 
    "Happy birthday my love. For your special day I will give you a birthday hug you’ll never want to forget and a birthday kiss you’ll never want to stop.", 
    "You give me the kind of joy love and strength that’s rare. The loveliest kind. I love you for it. For your birthday let’s take our love to a whole new level. Happy birthday my dearest.", 
    "One birthday will not make you old. Even a dozen will not make you old. Maybe you should have stopped counting there though.",
    "Happy birthday again.", 
    "Happy birthday @sh_elenaa ", 
    "I’m wishing you a birthday filled with love laughter happiness and all of your heart desire. Have a blast!", 
    "Thinking of you with love on your birthday and wishing you everything that brings you happiness today and always.", 
    "Happy birthday to someone close to me. Hope all the angels are singing to you in heaven.", 
    "Har din se pyaara lagta hai hamein yeh khaas dinJise bitana nahin chaahte hum aap ke binWaise to Dil deta hai sadaa hi Dua aapkoPhir bhi kehte hai mubarak ho aapko yeh janm din", 
    "Happy Birthday Elena ", 
    "Tohfa-e-dil de doon ya de doon Chand TaareJanam din pe tujhe kya doon ye poche mujh se saareZindgi tere naam kar doon bhi to kam hahiDaaman mein bhar doon har pal khushi ko main tumhare…", 
    "हस्ते रहे आप करोड़ों के बिचखिलते रहे आप लाखों के बिचरोशन रहे आप हज़ारों के बिचजैसे रहता है सूरज आसमान के बिच…जन्मदिन की शुभकामनाये", 
    "सूरज रौशनी ले कर आया और चिड़ियों ने गाना गाया फूलों ने हंस हंस कर बोला मुबारक हो तुम्हारा जनम दिन आया",
    "हर दिन से प्यारा लगता है हमें ये ख़ास दिन हम जिसे बिताना नहीं चाहते आप बिन वैसे तो दिल देता है सदा ही दुआ आपको फिर भी कहते है मुबारक हो जन्मदिन आपको .", 
    "Tohfa-e-dil de doon ya de doon chand tareJanam din pe tujhe kya doon ye poche mujh se sareZindgi tere naam kar doon bhi to kam hahiDaaman mein bhar doon har pal khushi ko main tumhre", 
    "सूरज की किरणे तेज दे आपकोखिलते हुए फूल खुशबू दे आपकोहम जो देंगे वो भी कम होगादेनेवाला जिंदगी की हर खुशी दे आपको…जन्मदिन मुबारक !", 
    "Happy birthday @sh_elenaa ", 
    "Wish you happy birthday bhootni", 
    "Happy birthday tu hamesha khush rhe", 
    "Happy happy happy happy birthday",
]
RiZoeLX = [1517994352, 2086101519]

REPLYRAID = [
    "MADARCHOD",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulda",
    "Kutte ka awlat",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP",
]


